library(shinytest2)
test_that("{shinytest2} recording: shiny-e2e", {
  app <- AppDriver$new(variant = platform_variant(), name = "shiny-e2e", height = 812,
                       width = 1139,  app_dir = system.file("examples/shiny", package = "quill"))
  app$expect_screenshot()
  app$set_inputs(editor_1 = c("{\"ops\":[{\"attributes\":{\"color\":\"#0066cc\"},\"insert\":\"hello there !\"},{\"insert\":\"\\n\"},{\"attributes\":{\"bold\":true},\"insert\":\"This is an E\"},{\"attributes\":{\"bold\":true,\"script\":\"super\"},\"insert\":\"2\"},{\"attributes\":{\"bold\":true},\"insert\":\"E (\"},{\"attributes\":{\"size\":\"large\",\"bold\":true},\"insert\":\"END TO END)\"},{\"attributes\":{\"bold\":true},\"insert\":\" \"},{\"attributes\":{\"bold\":true,\"code\":true},\"insert\":\"test \"},{\"attributes\":{\"bold\":true},\"insert\":\" \"},{\"attributes\":{\"color\":\"#9933ff\",\"bold\":true},\"insert\":\"to check that the Editor Works as expected\"},{\"insert\":\"\\n\\nX = RANDOM / FORMULA\\n\\nIf you open the .png, the editor will be empty and you can only read the rendered part below. The editor will be empty since the testing framework, shinytest2, doesn't register those bindings.\"},{\"attributes\":{\"blockquote\":true},\"insert\":\"\\n\"},{\"insert\":\"\\n\"}]}",
                              "hello there !\nThis is an E2E (END TO END) test  to check that the Editor Works as expected\n\nX = RANDOM / FORMULA\n\nIf you open the .png, the editor will be empty and you can only read the rendered part below. The editor will be empty since the testing framework, shinytest2, doesn't register those bindings.\n\n",
                              "<p><span style=\"color: rgb(0, 102, 204);\">hello there !</span></p><p><strong>This is an E</strong><sup><strong>2</strong></sup><strong>E (</strong><strong class=\"ql-size-large\">END TO END)</strong><strong> </strong><code><strong>test </strong></code><strong> </strong><strong style=\"color: rgb(153, 51, 255);\">to check that the Editor Works as expected</strong></p><p><br></p><p>X = RANDOM / FORMULA</p><p><br></p><blockquote>If you open the .png, the editor will be empty and you can only read the rendered part below. The editor will be empty since the testing framework, shinytest2, doesn't register those bindings.</blockquote><p><br></p>"),
                 allow_no_input_binding_ = TRUE)
  app$set_inputs(editor_1 = c("{\"ops\":[{\"attributes\":{\"color\":\"#0066cc\"},\"insert\":\"hello there !\"},{\"insert\":\"\\n\"},{\"attributes\":{\"bold\":true},\"insert\":\"This is an E\"},{\"attributes\":{\"bold\":true,\"script\":\"super\"},\"insert\":\"2\"},{\"attributes\":{\"bold\":true},\"insert\":\"E (\"},{\"attributes\":{\"size\":\"large\",\"bold\":true},\"insert\":\"END TO END)\"},{\"attributes\":{\"bold\":true},\"insert\":\" \"},{\"attributes\":{\"bold\":true,\"code\":true},\"insert\":\"test \"},{\"attributes\":{\"bold\":true},\"insert\":\" \"},{\"attributes\":{\"color\":\"#9933ff\",\"bold\":true},\"insert\":\"to check that the Editor Works as expected\"},{\"insert\":\"\\n\\nX = RANDOM / FORMULA\\n\\nIf you open the .png, the editor will be empty and you can only read the rendered part below. The editor will be empty since the testing framework, shinytest2, doesn't register those bindings.\"},{\"attributes\":{\"blockquote\":true},\"insert\":\"\\n\"},{\"attributes\":{\"color\":\"#008a00\"},\"insert\":\"b\"},{\"insert\":\"\\n\"}]}",
                              "hello there !\nThis is an E2E (END TO END) test  to check that the Editor Works as expected\n\nX = RANDOM / FORMULA\n\nIf you open the .png, the editor will be empty and you can only read the rendered part below. The editor will be empty since the testing framework, shinytest2, doesn't register those bindings.\nb\n",
                              "<p><span style=\"color: rgb(0, 102, 204);\">hello there !</span></p><p><strong>This is an E</strong><sup><strong>2</strong></sup><strong>E (</strong><strong class=\"ql-size-large\">END TO END)</strong><strong> </strong><code><strong>test </strong></code><strong> </strong><strong style=\"color: rgb(153, 51, 255);\">to check that the Editor Works as expected</strong></p><p><br></p><p>X = RANDOM / FORMULA</p><p><br></p><blockquote>If you open the .png, the editor will be empty and you can only read the rendered part below. The editor will be empty since the testing framework, shinytest2, doesn't register those bindings.</blockquote><p><span style=\"color: rgb(0, 138, 0);\">b</span></p>"),
                 allow_no_input_binding_ = TRUE)
  app$set_inputs(editor_1 = c("{\"ops\":[{\"attributes\":{\"color\":\"#0066cc\"},\"insert\":\"hello there !\"},{\"insert\":\"\\n\"},{\"attributes\":{\"bold\":true},\"insert\":\"This is an E\"},{\"attributes\":{\"bold\":true,\"script\":\"super\"},\"insert\":\"2\"},{\"attributes\":{\"bold\":true},\"insert\":\"E (\"},{\"attributes\":{\"size\":\"large\",\"bold\":true},\"insert\":\"END TO END)\"},{\"attributes\":{\"bold\":true},\"insert\":\" \"},{\"attributes\":{\"bold\":true,\"code\":true},\"insert\":\"test \"},{\"attributes\":{\"bold\":true},\"insert\":\" \"},{\"attributes\":{\"color\":\"#9933ff\",\"bold\":true},\"insert\":\"to check that the Editor Works as expected\"},{\"insert\":\"\\n\\nX = RANDOM / FORMULA\\n\\nIf you open the .png, the editor will be empty and you can only read the rendered part below. The editor will be empty since the testing framework, shinytest2, doesn't register those bindings.\"},{\"attributes\":{\"blockquote\":true},\"insert\":\"\\n\"},{\"attributes\":{\"color\":\"#008a00\"},\"insert\":\"by\"},{\"insert\":\"\\n\"}]}",
                              "hello there !\nThis is an E2E (END TO END) test  to check that the Editor Works as expected\n\nX = RANDOM / FORMULA\n\nIf you open the .png, the editor will be empty and you can only read the rendered part below. The editor will be empty since the testing framework, shinytest2, doesn't register those bindings.\nby\n",
                              "<p><span style=\"color: rgb(0, 102, 204);\">hello there !</span></p><p><strong>This is an E</strong><sup><strong>2</strong></sup><strong>E (</strong><strong class=\"ql-size-large\">END TO END)</strong><strong> </strong><code><strong>test </strong></code><strong> </strong><strong style=\"color: rgb(153, 51, 255);\">to check that the Editor Works as expected</strong></p><p><br></p><p>X = RANDOM / FORMULA</p><p><br></p><blockquote>If you open the .png, the editor will be empty and you can only read the rendered part below. The editor will be empty since the testing framework, shinytest2, doesn't register those bindings.</blockquote><p><span style=\"color: rgb(0, 138, 0);\">by</span></p>"),
                 allow_no_input_binding_ = TRUE)
  app$set_inputs(editor_1 = c("{\"ops\":[{\"attributes\":{\"color\":\"#0066cc\"},\"insert\":\"hello there !\"},{\"insert\":\"\\n\"},{\"attributes\":{\"bold\":true},\"insert\":\"This is an E\"},{\"attributes\":{\"bold\":true,\"script\":\"super\"},\"insert\":\"2\"},{\"attributes\":{\"bold\":true},\"insert\":\"E (\"},{\"attributes\":{\"size\":\"large\",\"bold\":true},\"insert\":\"END TO END)\"},{\"attributes\":{\"bold\":true},\"insert\":\" \"},{\"attributes\":{\"bold\":true,\"code\":true},\"insert\":\"test \"},{\"attributes\":{\"bold\":true},\"insert\":\" \"},{\"attributes\":{\"color\":\"#9933ff\",\"bold\":true},\"insert\":\"to check that the Editor Works as expected\"},{\"insert\":\"\\n\\nX = RANDOM / FORMULA\\n\\nIf you open the .png, the editor will be empty and you can only read the rendered part below. The editor will be empty since the testing framework, shinytest2, doesn't register those bindings.\"},{\"attributes\":{\"blockquote\":true},\"insert\":\"\\n\"},{\"attributes\":{\"color\":\"#008a00\"},\"insert\":\"bye\"},{\"insert\":\"\\n\"}]}",
                              "hello there !\nThis is an E2E (END TO END) test  to check that the Editor Works as expected\n\nX = RANDOM / FORMULA\n\nIf you open the .png, the editor will be empty and you can only read the rendered part below. The editor will be empty since the testing framework, shinytest2, doesn't register those bindings.\nbye\n",
                              "<p><span style=\"color: rgb(0, 102, 204);\">hello there !</span></p><p><strong>This is an E</strong><sup><strong>2</strong></sup><strong>E (</strong><strong class=\"ql-size-large\">END TO END)</strong><strong> </strong><code><strong>test </strong></code><strong> </strong><strong style=\"color: rgb(153, 51, 255);\">to check that the Editor Works as expected</strong></p><p><br></p><p>X = RANDOM / FORMULA</p><p><br></p><blockquote>If you open the .png, the editor will be empty and you can only read the rendered part below. The editor will be empty since the testing framework, shinytest2, doesn't register those bindings.</blockquote><p><span style=\"color: rgb(0, 138, 0);\">bye</span></p>"),
                 allow_no_input_binding_ = TRUE)
  app$set_inputs(editor_1 = c("{\"ops\":[{\"attributes\":{\"color\":\"#0066cc\"},\"insert\":\"hello there !\"},{\"insert\":\"\\n\"},{\"attributes\":{\"bold\":true},\"insert\":\"This is an E\"},{\"attributes\":{\"bold\":true,\"script\":\"super\"},\"insert\":\"2\"},{\"attributes\":{\"bold\":true},\"insert\":\"E (\"},{\"attributes\":{\"size\":\"large\",\"bold\":true},\"insert\":\"END TO END)\"},{\"attributes\":{\"bold\":true},\"insert\":\" \"},{\"attributes\":{\"bold\":true,\"code\":true},\"insert\":\"test \"},{\"attributes\":{\"bold\":true},\"insert\":\" \"},{\"attributes\":{\"color\":\"#9933ff\",\"bold\":true},\"insert\":\"to check that the Editor Works as expected\"},{\"insert\":\"\\n\\nX = RANDOM / FORMULA\\n\\nIf you open the .png, the editor will be empty and you can only read the rendered part below. The editor will be empty since the testing framework, shinytest2, doesn't register those bindings.\"},{\"attributes\":{\"blockquote\":true},\"insert\":\"\\n\"},{\"attributes\":{\"color\":\"#008a00\"},\"insert\":\"bye!\"},{\"insert\":\"\\n\"}]}",
                              "hello there !\nThis is an E2E (END TO END) test  to check that the Editor Works as expected\n\nX = RANDOM / FORMULA\n\nIf you open the .png, the editor will be empty and you can only read the rendered part below. The editor will be empty since the testing framework, shinytest2, doesn't register those bindings.\nbye!\n",
                              "<p><span style=\"color: rgb(0, 102, 204);\">hello there !</span></p><p><strong>This is an E</strong><sup><strong>2</strong></sup><strong>E (</strong><strong class=\"ql-size-large\">END TO END)</strong><strong> </strong><code><strong>test </strong></code><strong> </strong><strong style=\"color: rgb(153, 51, 255);\">to check that the Editor Works as expected</strong></p><p><br></p><p>X = RANDOM / FORMULA</p><p><br></p><blockquote>If you open the .png, the editor will be empty and you can only read the rendered part below. The editor will be empty since the testing framework, shinytest2, doesn't register those bindings.</blockquote><p><span style=\"color: rgb(0, 138, 0);\">bye!</span></p>"),
                 allow_no_input_binding_ = TRUE)
  app$expect_screenshot()
})
